---

- name: install ForgeRock OpenAM
  copy:
    src: "../files/AM-eval-{{ am_version }}.war"
    dest: "{{ tomcat_path }}/webapps/am.war"
    owner: "{{ tomcat_user }}"
    group: "{{ tomcat_group }}"