---

# installing tomcat https://www.rosehosting.com/blog/install-tomcat-9-on-an-ubuntu-16-04-vps/

- name: add user group
  group:
    name: "{{ tomcat_group }}"
    state: present

- name: add user
  user:
    name: "{{ tomcat_user }}"
    group: "{{ tomcat_group }}"
    state: present

- name: unarchive tarball
  unarchive:
    src: "../files/apache-tomcat-{{ tomcat_version }}.tar.gz"
    dest: "{{ tomcat_parent }}"
    owner: "{{ tomcat_user }}"
    group: "{{ tomcat_group }}"

- name: set owner for extracted files
  file:
    path: "{{ tomcat_parent }}/apache-tomcat-{{ tomcat_version }}"
    owner: "{{ tomcat_user }}"
    group: "{{ tomcat_group }}"
    mode: 0755
    recurse: yes

- name: symlink to desired path
  file:
    src: "{{ tomcat_parent }}/apache-tomcat-{{ tomcat_version }}"
    dest: "{{ tomcat_path }}"
    state: "link"
    owner: "{{ tomcat_user }}"
    group: "{{ tomcat_group }}"
    mode: 0755

- name: configure server
  template:
    src: "server.xml"
    dest: "{{ tomcat_path }}/conf/"
    owner: "{{ tomcat_user }}"
    group: "{{ tomcat_group }}"

- name: configure users
  template:
    src: "tomcat-users.xml"
    dest: "{{ tomcat_path }}/conf/"
    owner: "{{ tomcat_user }}"
    group: "{{ tomcat_group }}"

- name: create systemd service
  template:
    src: "tomcat.service"
    dest: "/etc/systemd/system/{{ tomcat_service_name }}.service"
    mode: 0755

- name: enable service
  service:
    name: "{{ tomcat_service_name }}.service"
    enabled: yes
  notify: restart service